name = "management-system-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "management-system-db"
database_id = "2e65d39f-96bc-4379-b15a-422bb844f3d4"

[[r2_buckets]]
binding = "FILES"
bucket_name = "management-system-files"

[vars]
ENVIRONMENT = "development"